# Generated by Django 3.2.8 on 2021-10-22 14:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date',
            field=models.DateField(default=datetime.datetime(2021, 10, 22, 14, 40, 21, 236210, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
