# Generated by Django 3.2.6 on 2021-11-19 15:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211025_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 19, 15, 35, 42, 480527, tzinfo=utc), verbose_name='Дата'),
        ),
    ]
